version: '2.4'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - peh-db

  peh-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: peh-labs
      MYSQL_USER: peh-labs-user
      MYSQL_PASSWORD: peh-labs-password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

  peh-capstone-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: peh-capstone-labs
      MYSQL_USER: peh-capstone-user
      MYSQL_PASSWORD: peh-capstone-password
    volumes:
      - db_data:/var/lib/mysql2
    ports:
      - 3307:3306

volumes:
  db_data: